language: python
sudo: false
python:
 - 3.6

branches:
  only:
  - master

matrix:
    include:
      - os: linux
        dist: xenial
      - os: linux
        dist: yakkety
      - os: linux
        dist: zesty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc
      - postgresql-client-9.6

env:
  - DJANGO_VERSION=1.11.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - travis_wait 240 pip install -r requirements.txt

notifications:
  email:
    on_success: never
    on_failure: always
  slack: powerpiper:fDpG2QMxg9NRjGuW8HsJJHF0

script:
    - echo "TODO"
