language: python
sudo: true
python:
 - 3.6

branches:
  only:
  - master

matrix:
    include:
      - os: linux
        dist: xenial
      - os: linux
        dist: yakkety
      - os: linux
        dist: zesty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc
      - postgresql-client-9.6
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_VERSION=1.11.7

before_script:
  - psql -c "CREATE DATABASE test_db ENCODING = 'UTF8';" -U postgres

test:
  adapter: postgresql
  database: travis_ci_test

install:
  - pip install -q Django==$DJANGO_VERSION
  - travis_wait 240 pip install -r requirements.txt

notifications:
  email:
    on_success: never
    on_failure: always
  slack: powerpiper:fEBF3prSwdbMzHrmXs6Pd4ut

script:
    - python $TRAVIS_BUILD_DIR/manage.py makemigrations
    - python $TRAVIS_BUILD_DIR/manage.py migrate
    - python $TRAVIS_BUILD_DIR/scripts/superuser.py --user=testuser --password=testpassword --email=test@email.com
    - python $TRAVIS_BUILD_DIR/manage.py collectstatic --noinput
    - python $TRAVIS_BUILD_DIR/tests.py
    - bash $TRAVIS_BUILD_DIR/scripts/build.sh powerpiper $TRAVIS_BUILD_DIR 3010
