language: python
sudo: required
python:
 - 3.6

branches:
  only:
  - master

matrix:
    include:
      - os: linux
        dist: xenial
      - os: linux
        dist: yakkety
      - os: linux
        dist: zesty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc
      - postgresql-client-9.6
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_VERSION=2.0

before_script:
  - sudo apt-get update -q
  - sudo apt-get install -y nginx
  - sudo rm -rf /etc/nginx/sites-enabled/default
  - sudo apt-get install -y xz-utils
  - psql -c "CREATE DATABASE test_db ENCODING = 'UTF8';" -U postgres
  - wget https://storage.googleapis.com/golang/go1.8.2.linux-amd64.tar.gz
  - sudo tar -C /usr/bin -xzf go1.8.2.linux-amd64.tar.gz
  - go get github.com/lib/pq
  - go get github.com/labstack/echo
  - go get github.com/labstack/echo/...
  - go get github.com/joho/godotenv
  - go get github.com/die-net/lrucache
  - export PATH=$PATH:/usr/bin/go/bin
  - export GOROOT=/usr/bin/go
  - go build
  - wget https://nodejs.org/dist/v8.6.0/node-v8.6.0-linux-x64.tar.xz
  - sudo tar -C /usr/local --strip-components 1 -xJf node-v8.6.0-linux-x64.tar.xz
  - ls -l /usr/local/bin/node
  - ls -l /usr/local/bin/npm
  - cd frontend
  - npm i
  - npm i -g pm2
  - export FRONTEND_PORT=3010
  - pm2 start npm --name "node" -- start
  - pm2 start $TRAVIS_BUILD_DIR/$PROJECT --name "api" --interpreter=bash
  - cd ../

test:
  adapter: postgresql
  database: travis_ci_test

install:
  - travis_wait 240 pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

notifications:
  email:
    on_success: never
    on_failure: always
  slack: powerpiper:fEBF3prSwdbMzHrmXs6Pd4ut

script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python scripts/superuser.py --user=testuser --password=testpassword --email=test@email.com
    - python manage.py collectstatic --noinput
    - python tests.py
    - travis_wait 360 bash scripts/build.sh 3010 8010
