sudo: required
language: node_js
node_js:
  - "8.6"

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: xenial

cache:
  directories:
    - node_modules

install:
  - npm install

cript:
  - npm run build
  - npm run lint
  #- npm run test

after_success:
  - npm run coverage

notifications:
  email:
    on_success: never
    on_failure: always
  slack: powerpiper:fEBF3prSwdbMzHrmXs6Pd4ut