# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Categoery')),
                ('slug', models.CharField(blank=True, max_length=120, null=True)),
                ('parsed', models.BooleanField(default=0, verbose_name='Parsed status')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Title')),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image')),
                ('url', models.URLField(verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Category', verbose_name='Categoery')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
